service: light-switch
provider:
    name: aws
    runtime: python3.6
    region: ${self:custom.region}
    stage: ${opt:stage, self:custom.defaultStage}
    profile: ${self:custom.profile}
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "ec2:Start*"
              - "ec2:Stop*"
              - "ec2:Describe*"
          Resource: "*"
custom:
    defaultStage: prod
    region: ${self:custom.${self:provider.stage}.region}
    profile: ${opt:profile, self:custom.${self:provider.stage}.profile, "default"}
    prod:
        profile: default
        region: "us-east-1"
functions:
    light_switch:
        environment:
            REGION: ${self:custom.region}
        handler: app.handler
        description: Light Switch Functions
        events:
            - schedule: 
                rate: cron(0 10 * * ? *)
                name: light_switch_morning_schedule
                description: 'This schedule is responsible to turn on or turn off instances'
            - schedule: 
                rate: cron(0 22 * * ? *)
                name: light_switch_night_schedule
                description: 'This schedule is responsible to turn on or turn off instances'
